/**
 * API contract types — mirror of the NestJS response envelope.
 *
 * Do not hand-edit: this file is regenerated by the backend `npm run sync:api`
 * from the OpenAPI spec, and local edits are overwritten. The copy kept here is
 * for editor autocomplete; if a field is missing, run the sync command rather
 * than adding it by hand.
 */

/** Wraps every successful list response. */
export interface PageMeta {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/** Standard success envelope returned by the `TransformInterceptor`. */
export interface ApiResponse<T> {
  data: T;
  meta?: PageMeta;
}

/** Standard error envelope returned by the `AllExceptionsFilter`. */
export interface ApiErrorBody {
  statusCode: number;
  code: string;
  message: string;
  details?: unknown;
  requestId?: string;
  path?: string;
  timestamp?: string;
}

/** Raised by the API client when a request fails. Carries the parsed error body. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly code: string,
    message: string,
    readonly details?: unknown,
    readonly requestId?: string,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

export type Locale = 'vi' | 'en';

export type Role = 'ADMIN' | 'MANAGER' | 'USER';

export type UserStatus = 'PENDING' | 'ACTIVE' | 'SUSPENDED';

export type AuthProvider = 'LOCAL' | 'GOOGLE';

export interface User {
  id: string;
  email: string;
  fullName: string;
  avatarUrl: string | null;
  locale: Locale;
  role: Role;
  status: UserStatus;
  authProvider: AuthProvider;
  emailVerifiedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Public shape of a user — hides the OAuth tokens and internal flags. */
export type PublicUser = Omit<User, 'emailVerifiedAt' | 'authProvider'>;

export interface Region {
  id: string;
  code: string;
  name: string;
  type: 'PROVINCE' | 'CITY' | 'DISTRICT';
  lat: number;
  lng: number;
}

export interface AuthTokens {
  accessToken: string;
  /** Present only when the client cannot hold cookies (native mobile). */
  refreshToken?: string;
}

export interface AuthSession {
  user: User;
  accessToken: string;
  expiresIn: number;
}
